# Generated by Django 2.0.3 on 2018-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('userName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('intro', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('userName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField()),
                ('intro', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(default='', max_length=100)),
                ('gameInfo', models.TextField()),
                ('gameAddress', models.CharField(max_length=500)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteId', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('heartRate', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemAthleteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteId', models.IntegerField()),
                ('itemId', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCoachRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachId', models.IntegerField()),
                ('itemId', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShakeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField()),
                ('athleteId', models.IntegerField()),
                ('handX', models.DecimalField(decimal_places=2, max_digits=4)),
                ('handY', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shoulderX', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shoulderY', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waistX', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waistY', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hipsX', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hipsY', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShootData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('data', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rapidTime', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shootTime', models.DateTimeField()),
                ('xPos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('yPos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShootItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='', max_length=100)),
                ('itemInfo', models.TextField()),
                ('itemRule', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('athleteId', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('target', models.CharField(max_length=100)),
                ('totalGrade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stageTime', models.DateTimeField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
