# Generated by Django 2.0.3 on 2018-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('userName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AthleteInfo',
        ),
        migrations.DeleteModel(
            name='CoachInfo',
        ),
    ]
