# Generated by Django 2.0.3 on 2018-06-29 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0002_auto_20180629_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='gameDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='heartratedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameAddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameInfo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='heartratedata',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itemathleterelation',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itemcoachrelation',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shakedata',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shootdata',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shootdata',
            name='shootTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shootitems',
            name='itemInfo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shootitems',
            name='itemRule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shootitems',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stageinfo',
            name='gameId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stageinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stageinfo',
            name='stageTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stageinfo',
            name='totalGrade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
