# Generated by Django 2.0.3 on 2018-07-12 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0003_auto_20180629_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shakedata',
            old_name='handX',
            new_name='beside_x',
        ),
        migrations.RenameField(
            model_name='shakedata',
            old_name='handY',
            new_name='beside_y',
        ),
        migrations.RenameField(
            model_name='shakedata',
            old_name='hipsX',
            new_name='up_data',
        ),
        migrations.RenameField(
            model_name='shootdata',
            old_name='rapidTime',
            new_name='rapid_time',
        ),
        migrations.RenameField(
            model_name='shootdata',
            old_name='shootTime',
            new_name='shoot_time',
        ),
        migrations.RenameField(
            model_name='shootdata',
            old_name='xPos',
            new_name='x_pos',
        ),
        migrations.RenameField(
            model_name='shootdata',
            old_name='yPos',
            new_name='y_pos',
        ),
        migrations.RemoveField(
            model_name='shakedata',
            name='hipsY',
        ),
        migrations.RemoveField(
            model_name='shakedata',
            name='shoulderX',
        ),
        migrations.RemoveField(
            model_name='shakedata',
            name='shoulderY',
        ),
        migrations.RemoveField(
            model_name='shakedata',
            name='waistX',
        ),
        migrations.RemoveField(
            model_name='shakedata',
            name='waistY',
        ),
        migrations.AddField(
            model_name='heartratedata',
            name='record_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shakedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shakedata',
            name='record_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shootdata',
            name='record_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
