# Generated by Django 2.0.3 on 2018-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0004_auto_20180712_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='gameDate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='heartratedata',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shakedata',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shootdata',
            name='shoot_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stageinfo',
            name='stageTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
