# Generated by Django 2.0.3 on 2018-07-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0005_auto_20180712_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShakeBesideData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField()),
                ('athleteId', models.IntegerField()),
                ('beside_x', models.DecimalField(decimal_places=2, max_digits=4)),
                ('beside_y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('record_time', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShakeUpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField()),
                ('athleteId', models.IntegerField()),
                ('up_data', models.DecimalField(decimal_places=2, max_digits=4)),
                ('record_time', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShakeData',
        ),
    ]
