# Generated by Django 2.0.3 on 2018-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0006_auto_20180713_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='heart_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('heart_time', models.CharField(max_length=200)),
                ('heart_date', models.CharField(max_length=200)),
                ('heart_rate', models.CharField(max_length=200)),
                ('average_rate', models.IntegerField(default=0)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_heart_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_shake_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shake_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('shake_date', models.CharField(max_length=200)),
                ('shake_time', models.CharField(max_length=200)),
                ('data', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('grade_date', models.CharField(max_length=200)),
                ('grade_time', models.CharField(max_length=200)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rapid_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('x_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_date', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
            ],
        ),
    ]
