# Generated by Django 2.0.3 on 2018-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0007_heart_data_record_heart_time_record_shake_time_shake_data_shoot_grade_shoot_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot_grade',
            name='grade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoot_grade',
            name='rapid_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoot_grade',
            name='x_pos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoot_grade',
            name='y_pos',
            field=models.CharField(max_length=200),
        ),
    ]
