# Generated by Django 2.0.3 on 2018-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0008_auto_20180909_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_heart_time',
            name='record_time',
        ),
        migrations.AddField(
            model_name='record_heart_time',
            name='end_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='record_heart_time',
            name='start_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
