# Generated by Django 2.0.3 on 2018-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0009_auto_20180913_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_shake_time',
            old_name='record_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='record_shake_time',
            old_name='type',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='shake_data',
            old_name='data',
            new_name='x_data',
        ),
        migrations.AddField(
            model_name='shake_data',
            name='y_data',
            field=models.TextField(null=True),
        ),
    ]
