# Generated by Django 2.0.3 on 2018-09-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0010_auto_20180913_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_report',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
