# Generated by Django 2.0.3 on 2018-10-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0011_shoot_report_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_heart_time',
            name='record_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='record_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shoot_grade',
            name='grade_detail_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='shoot_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shake_data',
            name='shake_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
