# Generated by Django 2.0.3 on 2018-10-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0012_auto_20181027_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_grade',
            name='heart_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_grade',
            name='x_shake',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_grade',
            name='y_shake',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='x_shake_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='y_shake_data',
            field=models.TextField(null=True),
        ),
    ]
