# Generated by Django 2.0.3 on 2018-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0014_auto_20181102_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_shake_time',
            old_name='remark',
            new_name='shake_data',
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='shake_detail_data',
            field=models.TextField(null=True),
        ),
    ]
