# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0015_auto_20181103_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_shake_time',
            old_name='shake_data',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='record_shake_time',
            old_name='shake_detail_data',
            new_name='shake_x_data',
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='shake_x_detail_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='shake_y_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='shake_y_detail_data',
            field=models.TextField(null=True),
        ),
    ]
