# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0016_auto_20181104_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_heart_time',
            name='is_process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record_shake_time',
            name='is_process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='is_process',
            field=models.IntegerField(default=0),
        ),
    ]
