# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-08 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0018_auto_20181108_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_athlete_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_coach_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_info', models.TextField(null=True)),
                ('item_rule', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
