# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0019_item_athlete_relation_item_coach_relation_shoot_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item_athlete_relation',
        ),
        migrations.DeleteModel(
            name='item_coach_relation',
        ),
        migrations.AddField(
            model_name='user_info',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
