# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0020_auto_20181108_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_up_shake_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('shake_x_data', models.TextField(null=True)),
                ('shake_x_detail_data', models.TextField(null=True)),
                ('shake_y_data', models.TextField(null=True)),
                ('shake_y_detail_data', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
