# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0021_record_up_shake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_report',
            name='x_up_shake_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='y_up_shake_data',
            field=models.TextField(null=True),
        ),
    ]
