# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0022_auto_20181203_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_report',
            name='x_shake_data_real',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='x_up_shake_data_real',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='y_shake_data_real',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoot_report',
            name='y_up_shake_data_real',
            field=models.TextField(null=True),
        ),
    ]
