# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0023_auto_20181206_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='shake_all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(default='', max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('end_time', models.CharField(default='', max_length=200)),
                ('beside_x_data', models.TextField(null=True)),
                ('beside_x_pos', models.TextField(null=True)),
                ('beside_y_data', models.TextField(null=True)),
                ('beside_y_pos', models.TextField(null=True)),
                ('up_x_data', models.TextField(null=True)),
                ('up_x_pos', models.TextField(null=True)),
                ('up_y_data', models.TextField(null=True)),
                ('up_y_pos', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='shoot_report',
            old_name='x_shake_data_real',
            new_name='x_shake_pos',
        ),
        migrations.RenameField(
            model_name='shoot_report',
            old_name='x_up_shake_data_real',
            new_name='x_up_shake_pos',
        ),
        migrations.RenameField(
            model_name='shoot_report',
            old_name='y_shake_data_real',
            new_name='y_shake_pos',
        ),
        migrations.RenameField(
            model_name='shoot_report',
            old_name='y_up_shake_data_real',
            new_name='y_up_shake_pos',
        ),
    ]
